---
title: "Developing Data Products Course Project"
author: "Fatma ElBadry"
date: "July 6, 2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

This Shiny App shows the effect of different parameters on MPG for the Motor trend dataset.

I used mtcars dataset in the analysis to explore the relationship between a set of variables and mpg(miles per gallon)

## More About the Dataset
### **Desription**
   The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973-74 models).
   
### **Format**
A data frame with 32 observations on 11 (numeric) variables.

[, 1]	mpg	Miles/(US) gallon
[, 2]	cyl	Number of cylinders
[, 3]	disp	Displacement (cu.in.)
[, 4]	hp	Gross horsepower
[, 5]	drat	Rear axle ratio
[, 6]	wt	Weight (1000 lbs)
[, 7]	qsec	1/4 mile time
[, 8]	vs	Engine (0 = V-shaped, 1 = straight)
[, 9]	am	Transmission (0 = automatic, 1 = manual)
[,10]	gear	Number of forward gears
[,11]	carb	Number of carburetors

## How this ShinyApp works

The user selects the variable from the drop down menu in the side bar to be plotted against the mpg.

Also,you can view the regression model for the selected variable in another tab

## App link

You can find this App from the following :

Also to view the source code:




